"""initial_schema

Revision ID: 4e89ccba3183
Revises: 
Create Date: 2026-06-08 10:37:32.242327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e89ccba3183'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aml_results',
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('triggered_rules', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_aml_results_account_id'), 'aml_results', ['account_id'], unique=False)
    op.create_index(op.f('ix_aml_results_risk_level'), 'aml_results', ['risk_level'], unique=False)
    op.create_index(op.f('ix_aml_results_transaction_id'), 'aml_results', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_aml_results_verified_at'), 'aml_results', ['verified_at'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('counterparty_account_id', sa.String(length=50), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kafka_offset', sa.Integer(), nullable=True),
    sa.Column('kafka_partition', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_aml_results_verified_at'), table_name='aml_results')
    op.drop_index(op.f('ix_aml_results_transaction_id'), table_name='aml_results')
    op.drop_index(op.f('ix_aml_results_risk_level'), table_name='aml_results')
    op.drop_index(op.f('ix_aml_results_account_id'), table_name='aml_results')
    op.drop_table('aml_results')
    # ### end Alembic commands ###
